name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Build
        run: |
          bun builder
          bun lint:fix

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "emails-${{ github.sha }}"
          path: "dist/emails.ts"
          retention-days: 7
        continue-on-error: true
